apiVersion: v1
kind: Namespace
metadata:
  name: astrogea
  labels:
    name: astrogea
    app: astrogea-distributed
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: astrogea-quota
  namespace: astrogea
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "16"
    limits.memory: 32Gi
    persistentvolumeclaims: "10"
